---

os: linux

dist: bionic

arch:
  - amd64
  - ppc64le

services:
  - docker
sudo: required

git:
  depth: false

language: go

go:
  - 1.12.x

script:
  - make docker-build

# after_success:
#   - bash <(curl -s https://codecov.io/bash) || echo "Failed to report code coverage!"
